import React, { useState } from 'react';
import { Bot, User, CheckCircle2, HelpCircle } from 'lucide-react';
import { audioService } from '../../services/audioService';
import { dataStoreService } from '../../services/firebaseService';

interface SectionProps {
  onUserDataChanged: () => void;
}

export const Section20MissionAiVsHuman: React.FC<SectionProps> = ({ onUserDataChanged }) => {
  const [selectedGuess, setSelectedGuess] = useState<'AI' | 'HUMAN' | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);

  const sampleText = `"Architecture is not about abstract forms; it is the physical bridge where human intelligence meets algorithmic precision to transform real-world complexity into elegant simplicity."`;
  const correctAnswer = 'AI'; // Generated by Synapse LLM

  const handleGuess = (guess: 'AI' | 'HUMAN') => {
    audioService.playClick();
    setSelectedGuess(guess);
    setIsAnswered(true);

    if (guess === correctAnswer) {
      audioService.playLevelUp();
      dataStoreService.awardXP('SYN-2026-9482', 200, 'MISSION-04', 'Mission 4: AI vs Human Turing', 'System Simulator');
      onUserDataChanged();
    }
  };

  return (
    <section className="full-section justify-center items-center">
      <div className="max-w-4xl mx-auto px-6 z-10 w-full text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1 rounded-full bg-purple-900/40 border border-purple-500/30 text-purple-300 font-mono text-xs mb-3">
          <HelpCircle className="w-3.5 h-3.5 text-amber-400" />
          <span>MISSION 04 • TURING TEST CHALLENGE</span>
        </div>
        <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-white mb-2">
          AI VS HUMAN TEXT DETECTOR
        </h2>
        <p className="font-sans text-xs sm:text-base text-gray-300 mb-8">
          Evaluate the technical excerpt below. Was it written by a Human Architect or Generated by Synapse LLM?
        </p>

        <div className="glass-card rounded-3xl p-6 sm:p-8 border border-purple-500/30 shadow-2xl mb-8">
          <div className="p-6 rounded-2xl bg-black/60 border border-purple-500/20 font-mono text-sm sm:text-base text-purple-200 leading-relaxed italic mb-8">
            {sampleText}
          </div>

          {!isAnswered ? (
            <div className="grid grid-cols-2 gap-4 max-w-md mx-auto">
              <button
                onClick={() => handleGuess('AI')}
                onMouseEnter={() => audioService.playHover()}
                className="glass-card hover:bg-purple-900/60 p-4 rounded-2xl border border-purple-400/40 flex items-center justify-center gap-3 font-mono font-bold text-cyan-300"
              >
                <Bot className="w-5 h-5 text-cyan-400" /> GENERATED BY AI
              </button>
              <button
                onClick={() => handleGuess('HUMAN')}
                onMouseEnter={() => audioService.playHover()}
                className="glass-card hover:bg-purple-900/60 p-4 rounded-2xl border border-purple-400/40 flex items-center justify-center gap-3 font-mono font-bold text-amber-300"
              >
                <User className="w-5 h-5 text-amber-400" /> WRITTEN BY HUMAN
              </button>
            </div>
          ) : (
            <div className={`p-5 rounded-2xl border font-mono text-sm ${
              selectedGuess === correctAnswer
                ? 'bg-emerald-950/70 border-emerald-500/40 text-emerald-300'
                : 'bg-red-950/70 border-red-500/40 text-red-300'
            }`}>
              {selectedGuess === correctAnswer ? (
                <div className="flex items-center justify-center gap-2">
                  <CheckCircle2 className="w-6 h-6 text-emerald-400" />
                  <span>CORRECT! GENERATED BY SYNAPSE LLM (+200 XP AWARDED)</span>
                </div>
              ) : (
                <span>INCORRECT! IT WAS GENERATED BY SYNAPSE LLM.</span>
              )}
            </div>
          )}
        </div>
      </div>
    </section>
  );
};
